name: Model Training and Evaluation CI

on:
  push:
    branches:
      - kernelridge

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DecisionTreeRegressor training (train.py)
        run: |
          python train.py

      - name: Run KernelRidge training (train2.py)
        run: |
          python train2.py

